using System.ServiceModel;

namespace Rayffer.PersonalPortfolio.Interfaces
{
    /// <summary>
    /// Base interface for WFC Service's client classes.
    /// </summary>
    /// <typeparam name="T">the class type which implements the Service's Client. </typeparam>
    /// <remarks>
    /// The class <typeparamref name="T"/> is usually a WFC autogenerated Service's client.
    /// </remarks>
    public interface IClientFactory<out T> where T : ICommunicationObject
    {
        /// <summary>
        /// Gets the Service's Endpoint name.
        /// </summary>
        /// <value>
        /// The name of the Endpoint.
        /// </value>
        string EndpointName { get; }

        /// <summary>
        /// Gets the Service's Remote address.
        /// </summary>
        /// <value>
        /// The Remote address.
        /// </value>
        string RemoteAddress { get; }

        /// <summary>
        /// Gets the Service's client instance.
        /// </summary>
        /// <returns>
        /// An instance of <typeparamref name="T" /> service's client.
        /// </returns>
        T GetServiceClientInstance();
    }
}